/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Student Grade Management API
 * OpenAPI spec version: 1.0
 */
import type { _CollectionModelObjectEmbedded } from './_collectionModelObjectEmbedded';
import type { Links } from './links';

export interface CollectionModelObject {
  _embedded?: _CollectionModelObjectEmbedded;
  _links?: Links;
}
