/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Student Grade Management API
 * OpenAPI spec version: 1.0
 */
import type { _CollectionModelEntityModelGradeEmbedded } from './_collectionModelEntityModelGradeEmbedded';
import type { Links } from './links';

export interface CollectionModelEntityModelGrade {
  _embedded?: _CollectionModelEntityModelGradeEmbedded;
  _links?: Links;
}
