/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Student Grade Management API
 * OpenAPI spec version: 1.0
 */
import type { _CollectionModelEntityModelModuleEmbedded } from './_collectionModelEntityModelModuleEmbedded';
import type { Links } from './links';

export interface CollectionModelEntityModelModule {
  _embedded?: _CollectionModelEntityModelModuleEmbedded;
  _links?: Links;
}
