/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Student Grade Management API
 * OpenAPI spec version: 1.0
 */
import type { Module } from './module';
import type { Student } from './student';

export interface Grade {
  id?: number;
  module?: Module;
  score?: number;
  student?: Student;
}
