/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Student Grade Management API
 * OpenAPI spec version: 1.0
 */

export interface GradeRequestBody {
  id?: number;
  module?: string;
  score?: number;
  student?: string;
}
