/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Student Grade Management API
 * OpenAPI spec version: 1.0
 */

export * from './_collectionModelEntityModelGradeEmbedded';
export * from './_collectionModelEntityModelModuleEmbedded';
export * from './_collectionModelEntityModelStudentEmbedded';
export * from './_collectionModelObjectEmbedded';
export * from './_collectionModelObjectEmbeddedObjectsItem';
export * from './abstractJsonSchemaPropertyObject';
export * from './addGradeBody';
export * from './collectionModelEntityModelGrade';
export * from './collectionModelEntityModelModule';
export * from './collectionModelEntityModelStudent';
export * from './collectionModelObject';
export * from './entityModelGrade';
export * from './entityModelModule';
export * from './entityModelStudent';
export * from './grade';
export * from './gradeRequestBody';
export * from './item';
export * from './itemProperties';
export * from './jsonSchema';
export * from './jsonSchemaDefinitions';
export * from './jsonSchemaProperties';
export * from './link';
export * from './links';
export * from './module';
export * from './moduleRequestBody';
export * from './representationModelObject';
export * from './student';
export * from './studentRequestBody';