/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Student Grade Management API
 * OpenAPI spec version: 1.0
 */
import type { ItemProperties } from './itemProperties';

export interface Item {
  properties?: ItemProperties;
  requiredProperties?: string[];
  type?: string;
}
