/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Student Grade Management API
 * OpenAPI spec version: 1.0
 */
import type { AbstractJsonSchemaPropertyObject } from './abstractJsonSchemaPropertyObject';

export type JsonSchemaProperties = {[key: string]: AbstractJsonSchemaPropertyObject};
