/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Student Grade Management API
 * OpenAPI spec version: 1.0
 */
import type { JsonSchemaDefinitions } from './jsonSchemaDefinitions';
import type { JsonSchemaProperties } from './jsonSchemaProperties';

export interface JsonSchema {
  $schema?: string;
  definitions?: JsonSchemaDefinitions;
  description?: string;
  properties?: JsonSchemaProperties;
  requiredProperties?: string[];
  title?: string;
  type?: string;
}
