/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Student Grade Management API
 * OpenAPI spec version: 1.0
 */
import type { Item } from './item';

export type JsonSchemaDefinitions = {[key: string]: Item};
