/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Student Grade Management API
 * OpenAPI spec version: 1.0
 */

export interface Link {
  deprecation?: string;
  href?: string;
  hreflang?: string;
  name?: string;
  profile?: string;
  templated?: boolean;
  title?: string;
  type?: string;
}
