/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Student Grade Management API
 * OpenAPI spec version: 1.0
 */

export interface StudentRequestBody {
  email?: string;
  firstName?: string;
  id?: number;
  lastName?: string;
  username?: string;
}
